services:
  backend:
    image: node:20-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - finix-net
  frontend:
    image: oven/bun:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bun dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - finix-net
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    networks:
      - finix-net

volumes:
  mongo-data:

networks:
  finix-net:
    driver: bridge
